name: benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Rebuild benchmarks
      run: benchmarks/build-all.sh 5

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Run benchmarks
      run: benchmarks/run-all.sh
